### PR TITLE
Update reports-exit-links.md

### PR DESCRIPTION
**Pull request by rishimittal2003**

### CODE REVIEW

**Comment by MicaPete** [comment]
@rishimittal2003  - have you signed the Adobe CLA?

**Comment by rishimittal2003** [comment]
I have not. How do I do that?

Rishi Mittal  |  Technology Consultant (Analytics & Audience Manager)  |  Adobe  |  p. 385.345.2606  |  c. 801.899.5827  |  rimittal@adobe.com<mailto:rimittal@adobe.com>

Please make a note of my upcoming business travel, vacation & holidays:
PTO – October 4th to October 16th

**Comment by MicaPete** [comment]
@rishimittal2003  - click Details next to **Adobe CLA signed**?

**Comment by gigazelle** [comment]
Hi rishimittal, thank you so much for your contribution! You'll need to sign the Adobe CLA before we can approve these changes. Click the 'Checks' tab, then click the link where it says 'sign the Adobe CLA'. Once it's signed, you can reopen this pull request and we'll get it merged.

We look forward to working with you!

**Pull request closed without merging**
