### PR TITLE
Clarify Analytics IP address scope

### PR DESCRIPTION
**Pull request by ittaibaratz**
Clarify that the IP list refers to Analytics Data Collection and not the Analytics UI.

### CODE REVIEW

**Comment by mcarriger** [comment]
Merging -- It looks like this is changing only the header name for clarification.

**Comment by mcarriger** [comment]
Ittai, will you please sign the Adobe Contributor License Agreement? (Sorry, I'm new to this, and it turns out that even Adobe employees have to sign it. ;) ) You can find it by clicking the "View details" button next to "mcarriger merged commit f8ccdff into AdobeDocs:master 15 hours ago."

The CLA is a one-time thing, and once you sign it, the CLA check will no longer fail, and I can merge your change again and publish.

Thanks so much!

**Comment by ittaibaratz** [comment]
> Ittai, will you please sign the Adobe Contributor License Agreement? (Sorry, I'm new to this, and it turns out that even Adobe employees have to sign it. ;) ) You can find it by clicking the "View details" button next to "mcarriger merged commit [f8ccdff](https://github.com/AdobeDocs/analytics.en/commit/f8ccdff8b76d18b2df48994dde2875f4387babed) into AdobeDocs:master 15 hours ago."
> 
> The CLA is a one-time thing, and once you sign it, the CLA check will no longer fail, and I can merge your change again and publish.
> 
> Thanks so much!

done!

**Comment by mcarriger** [comment]
Thanks! I updated the file on CORP via https://git.corp.adobe.com/AdobeDocs/analytics.en/pull/1289, and it's published.

Thanks so much for your help!

**Pull request merged**
