### PR TITLE
Bug Fix Needed

### PR DESCRIPTION
**Pull request by kenmckell**
Please ensure version 3.1 is deployed as 3.0 has a bad cookie expiration bug that needs to be fixed.

### CODE REVIEW

**Comment by MicaPete** [comment]
@kenmckell - Tomorrow, I will copy this over to the repo on git.corp.adobe.com. The repo on github.com is a mirror but will get overwritten next time we make changes to the former.

**Comment by kenmckell** [comment]
D’oh!   Should have done this on the corp github.  Thanks! 😊


Ken McKell  |  Senior Consultant  |  Adobe Inc.  |  T 385 345 1742  |  C 801 616 7576  |  ***@***.******@***.***>  |  Lehi, Utah (Mountain Time)

**Comment by MicaPete** [comment]
@kenmckell 
https://experienceleague.adobe.com/docs/analytics/implementation/vars/plugins/getvalonce.html

**Comment by kenmckell** [comment]
Thanks!! 😊


Ken McKell  |  Senior Consultant  |  Adobe Inc.  |  T 385 345 1742  |  C 801 616 7576  |  ***@***.******@***.***>  |  Lehi, Utah (Mountain Time)

**Pull request closed without merging**
